<?php

/**
 * @file
 * Contains ml_page.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ml_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ml_page module.
    case 'help.page.ml_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

